#!/usr/bin/env python

import sys
import re
import socket
import transport
from os import system

'''
This code is designed to read in a branch file
    and then spawn a bunch of severs
'''


def main(args):
    if len(args) < 2:
        print("Usage: %s branch_file" %(args[0]))
        sys.exit(1)

    branch_file = args[1]

    regex = r'(.*?)\s(.*?)\s(.*)'
    with open(branch_file, "r") as file:
        for line in file:
            matches = re.match(regex, line, re.M | re.I )

            branch_name = matches.group(1)
            branch_ip = matches.group(2).strip()
            branch_port = int(matches.group(3).strip())
            make_server(branch_name, branch_ip, branch_port)

def make_server(name, ip, port):
    command = "./branch %s %d &" %(name,port)
    system(command)

if __name__ == '__main__':
    main(sys.argv)
